Repository nf-core/test-datasets, pull requests merged in 2023-05, with the labels that each got.

#868 add chr21 gtf
  README.md
  data/genomics/homo_sapiens/genome/chr21/sequence/chr21_gencode.gtf
Labels: Ready to review

#813 Added Atoplex bed file
  genome/NC_045512.2/amplicon/ nCoV-2019.atoplex.V1.bed
Labels: enhancement, Ready to review

#884 add missing cellranger data info
  README.md
Labels: enhancement
